# Generated by Django 3.0.7 on 2021-02-21 15:18

from django.db import migrations
from home.models import CategoryType, Category

def add_category_type_data(apps, schema_editor):
    expenses = CategoryType(id=1, type_name="Expenses")
    expenses.save()
    income = CategoryType(id=2, type_name="Income")
    income.save()

def add_categories(apps, schema_editor):
    category_1 = Category(category_type=1, name="Food")
    category_1.save()
    category_2 = Category(category_type=1, name="Bills")
    category_2.save()
    category_3 = Category(category_type=1, name="Shopping")
    category_3.save()
    category_4 = Category(category_type=2, name="Salary")
    category_4.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_category_type_data),
        migrations.RunPython(add_categories),
    ]
