# Generated by Django 3.0.7 on 2020-07-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='account', max_length=50),
        ),
    ]
