# Generated by Django 3.0.7 on 2020-07-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200712_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='Personal Account', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_income',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_spendings',
            field=models.FloatField(default=0),
        ),
    ]
